# Generated by Django 5.1.1 on 2024-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, editable=False, null=True),
        ),
    ]
