# Generated by Django 5.1.1 on 2024-09-05 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tweet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_on',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
    ]
