# Generated by Django 5.1.1 on 2024-09-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_tweet_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='use',
            new_name='user',
        ),
    ]
