# Generated by Django 5.1.1 on 2024-09-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_use_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
